import { Connection, PublicKey, TransactionInstruction } from '@solana/web3.js';
import { TOKEN_2022_PROGRAM_ID } from '@solana/spl-token';

export { generateDummyElgamalKeys, generateDummyAesKey, deriveElGamalKeypair } from './keys';

export class PrivacyOpsBuilder {
  constructor(
    private _connection: Connection,
    private mint: PublicKey,
    private owner: PublicKey,
  ) {}

  compileDepositInstruction(
    tokenAccount: PublicKey,
    amount: bigint,
    decimals: number,
  ): TransactionInstruction {
    const data = Buffer.alloc(11);
    data.writeUInt8(27, 0);
    data.writeUInt8(5, 1);
    data.writeBigUInt64LE(amount, 2);
    data.writeUInt8(decimals, 10);

    return new TransactionInstruction({
      programId: TOKEN_2022_PROGRAM_ID,
      keys: [
        { pubkey: tokenAccount, isSigner: false, isWritable: true },
        { pubkey: this.mint, isSigner: false, isWritable: false },
        { pubkey: this.owner, isSigner: true, isWritable: false },
      ],
      data,
    });
  }

  compileSettlePendingInstruction(tokenAccount: PublicKey): TransactionInstruction {
    const data = Buffer.alloc(2);
    data.writeUInt8(27, 0);
    data.writeUInt8(8, 1);

    return new TransactionInstruction({
      programId: TOKEN_2022_PROGRAM_ID,
      keys: [
        { pubkey: tokenAccount, isSigner: false, isWritable: true },
        { pubkey: this.owner, isSigner: true, isWritable: false },
      ],
      data,
    });
  }

  buildTransferInstruction(
    _senderTokenAccount: PublicKey,
    _recipientTokenAccount: PublicKey,
    _amount: bigint,
  ): TransactionInstruction {
    throw new Error(
      'Confidential transfers require ZK proofs (range, equality, ciphertext validity) ' +
        'that must be generated by a Rust proof service. ' +
        'See docs/SSS-3.md for the proof service architecture.',
    );
  }

  buildWithdrawInstruction(
    _tokenAccount: PublicKey,
    _amount: bigint,
    _decimals: number,
  ): TransactionInstruction {
    throw new Error(
      'Confidential withdrawals require ZK proofs (range, equality) ' +
        'that must be generated by a Rust proof service. ' +
        'See docs/SSS-3.md for the proof service architecture.',
    );
  }
}
