/**
 * Unit tests for the confidential transfer SDK utilities.
 *
 * These tests verify instruction *construction* only — they do NOT send transactions
 * to a validator. ConfigureAccount always requires a PubkeyValidity ZK proof that
 * can only be generated by the `solana-zk-sdk` Rust crate.
 *
 * Data layout specs sourced from:
 *  https://docs.rs/spl-token-2022/latest/spl_token_2022/extension/confidential_transfer/instruction/
 */

import { describe, it, expect } from 'vitest';
import { PublicKey, SYSVAR_INSTRUCTIONS_PUBKEY } from '@solana/web3.js';
import { TOKEN_2022_PROGRAM_ID } from '@solana/spl-token';
import {
  createConfigureAccountInstruction,
  createDepositInstruction,
  createApplyPendingBalanceInstruction,
  generateDummyElgamalKeys,
  generateTestElGamalKeypair,
  generateDummyAesKey,
  encryptDecryptableZero,
  deriveElGamalKeypair,
  parseConfidentialTransferAccountState,
  CONFIDENTIAL_TRANSFER_ACCOUNT_EXTENSION_LENGTH,
  CONFIDENTIAL_TRANSFER_ELGAMAL_SEED_MESSAGE,
  CONFIDENTIAL_TRANSFER_AE_KEY_SEED_MESSAGE,
  CONFIDENTIAL_TRANSFER_EMPTY_PUBLIC_SEED,
  ZK_ELGAMAL_PROGRAM_DISABLED_NOTICE,
  encryptDecryptableBalance,
  decryptDecryptableBalance,
  deriveConfidentialKeysFromSignatures,
} from '../src/confidential';

const DUMMY_PUBKEY = new PublicKey('11111111111111111111111111111111');
const DUMMY_PUBKEY_2 = new PublicKey('So11111111111111111111111111111111111111112');

// ─────────────────────────────────────────────────────────────
//  keys.ts
// ─────────────────────────────────────────────────────────────
describe('Confidential Transfer – keys.ts', () => {
  it('generateDummyElgamalKeys returns 32-byte keys', () => {
    const { publicKey, secretKey } = generateDummyElgamalKeys();
    expect(publicKey).toBeInstanceOf(Uint8Array);
    expect(publicKey.length).toBe(32);
    expect(secretKey).toBeInstanceOf(Uint8Array);
    expect(secretKey.length).toBe(32);
  });

  it('generateTestElGamalKeypair is an alias for generateDummyElgamalKeys', () => {
    const a = generateDummyElgamalKeys();
    const b = generateTestElGamalKeypair();
    expect(a.publicKey.length).toBe(b.publicKey.length);
    expect(a.secretKey.length).toBe(b.secretKey.length);
  });

  it('generateDummyAesKey returns 16 bytes', () => {
    const key = generateDummyAesKey();
    expect(key).toBeInstanceOf(Uint8Array);
    expect(key.length).toBe(16);
  });

  it('encryptDecryptableZero returns 36 bytes', () => {
    const aesKey = generateDummyAesKey();
    const result = encryptDecryptableZero(aesKey);
    expect(result).toBeInstanceOf(Uint8Array);
    expect(result.length).toBe(36);
  });

  it('encryptDecryptableZero produces different nonces on each call', () => {
    const aesKey = generateDummyAesKey();
    const a = encryptDecryptableZero(aesKey);
    const b = encryptDecryptableZero(aesKey);
    // Nonce is first 12 bytes — should differ (random)
    expect(a.slice(0, 12)).not.toEqual(b.slice(0, 12));
  });

  it('encryptDecryptableZero throws for wrong key length', () => {
    expect(() => encryptDecryptableZero(new Uint8Array(8))).toThrow('AES key must be 16 bytes');
    expect(() => encryptDecryptableZero(new Uint8Array(32))).toThrow('AES key must be 16 bytes');
  });

  it('deriveElGamalKeypair always throws (Rust-only)', () => {
    expect(() => deriveElGamalKeypair(null, null)).toThrow('solana-zk-sdk Rust crate');
  });
});

// ─────────────────────────────────────────────────────────────
//  createConfigureAccountInstruction
//  Expected data: 47 bytes
//    [0]     27 (ConfidentialTransferExtension)
//    [1]     2  (ConfigureAccount)
//    [2-37]  decryptable_zero_balance (PodAeCiphertext, 36 bytes)
//    [38-45] maximum_pending_balance_credit_counter (PodU64, 8 bytes LE)
//    [46]    proof_instruction_offset (i8)
//  Accounts: [tokenAccount writable, mint, SYSVAR_INSTRUCTIONS, owner signer]
// ─────────────────────────────────────────────────────────────
describe('Confidential Transfer – createConfigureAccountInstruction', () => {
  const makeIx = () => {
    const decryptableZero = encryptDecryptableZero(generateDummyAesKey());
    return createConfigureAccountInstruction(
      DUMMY_PUBKEY, // tokenAccount
      DUMMY_PUBKEY_2, // mint
      DUMMY_PUBKEY, // owner
      decryptableZero,
      65536n,
      0,
      DUMMY_PUBKEY, // contextStateAccount
    );
  };

  it('targets TOKEN_2022_PROGRAM_ID', () => {
    expect(makeIx().programId.toBase58()).toBe(TOKEN_2022_PROGRAM_ID.toBase58());
  });

  it('has exactly 4 account metas [tokenAccount, mint, context_state, owner]', () => {
    const ix = makeIx();
    expect(ix.keys.length).toBe(4);
    expect(ix.keys[0].isWritable).toBe(true); // tokenAccount writable
    expect(ix.keys[1].isWritable).toBe(false); // mint read-only
    expect(ix.keys[2].pubkey.toBase58()).toBe(DUMMY_PUBKEY.toBase58()); // contextStateAccount
    expect(ix.keys[2].isSigner).toBe(false);
    expect(ix.keys[3].isSigner).toBe(true); // owner must sign
  });

  it('data starts with [27, 2] (ConfidentialTransferExtension + ConfigureAccount)', () => {
    const ix = makeIx();
    expect(ix.data[0]).toBe(27);
    expect(ix.data[1]).toBe(2);
  });

  it('data is exactly 47 bytes (2 + 36 PodAeCiphertext + 8 PodU64 + 1 i8)', () => {
    expect(makeIx().data.length).toBe(47);
  });

  it('default maxPendingBalanceCredits (65536) is encoded as PodU64 at bytes [38-45]', () => {
    const ix = makeIx();
    // Read PodU64 LE at offset 38
    const low = (ix.data as Buffer).readUInt32LE(38);
    const high = (ix.data as Buffer).readUInt32LE(42);
    const val = BigInt(low) + BigInt(high) * 0x100000000n;
    expect(val).toBe(65536n);
  });

  it('default proof_instruction_offset (0) is at byte [46]', () => {
    const ix = makeIx();
    expect((ix.data as Buffer).readInt8(46)).toBe(0);
  });

  it('throws when decryptableZeroBalance is not 36 bytes', () => {
    expect(() =>
      createConfigureAccountInstruction(
        DUMMY_PUBKEY,
        DUMMY_PUBKEY,
        DUMMY_PUBKEY,
        new Uint8Array(16), // wrong size
        65536n,
        0,
        DUMMY_PUBKEY,
      ),
    ).toThrow('36 bytes');
  });

  it('custom maxPendingBalanceCredits and proofOffset are encoded correctly', () => {
    const decryptableZero = encryptDecryptableZero(generateDummyAesKey());
    const ix = createConfigureAccountInstruction(
      DUMMY_PUBKEY,
      DUMMY_PUBKEY,
      DUMMY_PUBKEY,
      decryptableZero,
      1000n, // custom counter
      -1, // inline ZK proof at offset -1
      // No contextStateAccount needed here since offset is -1
    );
    // PodU64 at offset 38
    const low = (ix.data as Buffer).readUInt32LE(38);
    const high = (ix.data as Buffer).readUInt32LE(42);
    expect(BigInt(low) + BigInt(high) * 0x100000000n).toBe(1000n);
    // i8 at offset 46
    expect((ix.data as Buffer).readInt8(46)).toBe(-1);
    // Account 2 should be SYSVAR_INSTRUCTIONS_PUBKEY
    expect(ix.keys[2].pubkey.toBase58()).toBe(SYSVAR_INSTRUCTIONS_PUBKEY.toBase58());
  });
});

// ─────────────────────────────────────────────────────────────
//  createDepositInstruction
//  Expected data: 11 bytes
//    [0]    27 (ConfidentialTransferExtension)
//    [1]    5  (Deposit)
//    [2-9]  amount (PodU64, 8 bytes LE)
//    [10]   decimals (u8)
//  Accounts: [tokenAccount writable, mint, owner signer]
// ─────────────────────────────────────────────────────────────
describe('Confidential Transfer – createDepositInstruction', () => {
  const AMOUNT = 100_000_000n;
  const DECIMALS = 6;

  const makeIx = () =>
    createDepositInstruction(DUMMY_PUBKEY, DUMMY_PUBKEY_2, DUMMY_PUBKEY, AMOUNT, DECIMALS);

  it('targets TOKEN_2022_PROGRAM_ID', () => {
    expect(makeIx().programId.toBase58()).toBe(TOKEN_2022_PROGRAM_ID.toBase58());
  });

  it('has exactly 3 account metas [tokenAccount, mint, owner]', () => {
    const ix = makeIx();
    expect(ix.keys.length).toBe(3);
    expect(ix.keys[0].isWritable).toBe(true);
    expect(ix.keys[1].isWritable).toBe(false);
    expect(ix.keys[2].isSigner).toBe(true);
  });

  it('data starts with [27, 5] (ConfidentialTransferExtension + Deposit)', () => {
    const ix = makeIx();
    expect(ix.data[0]).toBe(27);
    expect(ix.data[1]).toBe(5);
  });

  it('data is exactly 11 bytes (2 + 8 PodU64 + 1 u8)', () => {
    expect(makeIx().data.length).toBe(11);
  });

  it('amount is encoded as PodU64 LE at bytes [2-9]', () => {
    const ix = makeIx();
    const low = (ix.data as Buffer).readUInt32LE(2);
    const high = (ix.data as Buffer).readUInt32LE(6);
    const decoded = BigInt(low) + BigInt(high) * 0x100000000n;
    expect(decoded).toBe(AMOUNT);
  });

  it('decimals is encoded at byte [10]', () => {
    expect((makeIx().data as Buffer).readUInt8(10)).toBe(DECIMALS);
  });
});

// ─────────────────────────────────────────────────────────────
//  createApplyPendingBalanceInstruction
//  Expected data: 46 bytes
//    [0]     27 (ConfidentialTransferExtension)
//    [1]     8  (ApplyPendingBalance)
//    [2-9]   expected_pending_balance_credit_counter (PodU64, 8 bytes LE)
//    [10-45] new_decryptable_available_balance (PodAeCiphertext, 36 bytes)
//  Accounts: [tokenAccount writable, owner signer]
// ─────────────────────────────────────────────────────────────
describe('Confidential Transfer – createApplyPendingBalanceInstruction', () => {
  const CREDIT_COUNTER = 3n;
  const CIPHERTEXT = new Uint8Array(36).fill(0xab);

  const makeIx = () =>
    createApplyPendingBalanceInstruction(DUMMY_PUBKEY, DUMMY_PUBKEY, CREDIT_COUNTER, CIPHERTEXT);

  it('targets TOKEN_2022_PROGRAM_ID', () => {
    expect(makeIx().programId.toBase58()).toBe(TOKEN_2022_PROGRAM_ID.toBase58());
  });

  it('has exactly 2 account metas [tokenAccount, owner]', () => {
    const ix = makeIx();
    expect(ix.keys.length).toBe(2);
    expect(ix.keys[0].isWritable).toBe(true);
    expect(ix.keys[1].isSigner).toBe(true);
  });

  it('data starts with [27, 8] (ConfidentialTransferExtension + ApplyPendingBalance)', () => {
    const ix = makeIx();
    expect(ix.data[0]).toBe(27);
    expect(ix.data[1]).toBe(8);
  });

  it('data is exactly 46 bytes (2 + 8 PodU64 + 36 PodAeCiphertext)', () => {
    expect(makeIx().data.length).toBe(46);
  });

  it('credit counter is encoded as PodU64 LE at bytes [2-9]', () => {
    const ix = makeIx();
    const low = (ix.data as Buffer).readUInt32LE(2);
    const high = (ix.data as Buffer).readUInt32LE(6);
    expect(BigInt(low) + BigInt(high) * 0x100000000n).toBe(CREDIT_COUNTER);
  });

  it('ciphertext is encoded at bytes [10-45]', () => {
    const ix = makeIx();
    const ciphertextSlice = new Uint8Array(
      (ix.data as Buffer).buffer,
      (ix.data as Buffer).byteOffset + 10,
      36,
    );
    expect(ciphertextSlice).toEqual(CIPHERTEXT);
  });

  it('throws when ciphertext is not 36 bytes', () => {
    expect(() =>
      createApplyPendingBalanceInstruction(DUMMY_PUBKEY, DUMMY_PUBKEY, 0n, new Uint8Array(16)),
    ).toThrow('36 bytes');
  });
});

// ─────────────────────────────────────────────────────────────
//  Token-2022 key derivation constants and ZK notice
// ─────────────────────────────────────────────────────────────
describe('Confidential Transfer – key derivation constants', () => {
  it('ELGAMAL_SEED_MESSAGE is ElGamalSecretKey', () => {
    expect(CONFIDENTIAL_TRANSFER_ELGAMAL_SEED_MESSAGE).toBe('ElGamalSecretKey');
  });
  it('AE_KEY_SEED_MESSAGE is AeKey', () => {
    expect(CONFIDENTIAL_TRANSFER_AE_KEY_SEED_MESSAGE).toBe('AeKey');
  });
  it('EMPTY_PUBLIC_SEED is zero-length', () => {
    expect(CONFIDENTIAL_TRANSFER_EMPTY_PUBLIC_SEED).toBeInstanceOf(Uint8Array);
    expect(CONFIDENTIAL_TRANSFER_EMPTY_PUBLIC_SEED.length).toBe(0);
  });
  it('ZK_ELGAMAL_PROGRAM_DISABLED_NOTICE mentions disabled', () => {
    expect(ZK_ELGAMAL_PROGRAM_DISABLED_NOTICE).toContain('disabled');
  });
});

// ─────────────────────────────────────────────────────────────
//  parseConfidentialTransferAccountState
// ─────────────────────────────────────────────────────────────
describe('Confidential Transfer – parseConfidentialTransferAccountState', () => {
  it('extension length is 295', () => {
    expect(CONFIDENTIAL_TRANSFER_ACCOUNT_EXTENSION_LENGTH).toBe(295);
  });

  it('parses minimal valid buffer and returns expected fields', () => {
    const data = new Uint8Array(CONFIDENTIAL_TRANSFER_ACCOUNT_EXTENSION_LENGTH);
    data[0] = 1; // approved
    data[261] = 1; // allow_confidential_credits
    data[262] = 1; // allow_non_confidential_credits
    // pending_balance_credit_counter at 263: 5
    data[263] = 5;
    data[264] = 0;
    data[265] = 0;
    data[266] = 0;
    data[267] = 0;
    data[268] = 0;
    data[269] = 0;
    data[270] = 0;
    const parsed = parseConfidentialTransferAccountState(data);
    expect(parsed.approved).toBe(true);
    expect(parsed.pendingBalanceCreditCounter).toBe(5n);
    expect(parsed.decryptableAvailableBalance.length).toBe(36);
    expect(parsed.pendingBalanceLo.length).toBe(64);
    expect(parsed.pendingBalanceHi.length).toBe(64);
    expect(parsed.elgamalPubkey.length).toBe(32);
  });

  it('throws when data is too short', () => {
    expect(() => parseConfidentialTransferAccountState(new Uint8Array(100))).toThrow(
      'at least 295',
    );
  });
});

// ─────────────────────────────────────────────────────────────
//  zk-sdk: deriveConfidentialKeysFromSignatures + encrypt/decrypt (optional)
// ─────────────────────────────────────────────────────────────
describe('Confidential Transfer – zk-keys (AeKey encrypt/decrypt)', () => {
  it('encryptDecryptableBalance returns 36 bytes when given amount and aeKey-like', () => {
    const fakeAeKey = {
      encrypt(amount: bigint) {
        return { toBytes: () => new Uint8Array(36).fill(0) };
      },
    };
    const out = encryptDecryptableBalance(0n, fakeAeKey);
    expect(out).toBeInstanceOf(Uint8Array);
    expect(out.length).toBe(36);
  });

  it('deriveConfidentialKeysFromSignatures + encrypt + decrypt round-trip (with zk-sdk)', async () => {
    const sig1 = new Uint8Array(64);
    const sig2 = new Uint8Array(64);
    for (let i = 0; i < 32; i++) sig1[i] = i + 1;
    for (let i = 0; i < 16; i++) sig2[i] = i + 10;
    let keys: Awaited<ReturnType<typeof deriveConfidentialKeysFromSignatures>>;
    try {
      keys = await deriveConfidentialKeysFromSignatures(sig1, sig2);
    } catch (e) {
      // WASM may not load in test env
      return;
    }
    expect(keys.elGamalPublicKey.length).toBe(32);
    expect(keys.elGamalSecretKey.length).toBe(32);
    const ct = encryptDecryptableBalance(
      1000n,
      keys.aesKey as { encrypt(a: bigint): { toBytes(): Uint8Array } },
    );
    expect(ct.length).toBe(36);
    const dec = await decryptDecryptableBalance(ct, keys.aesKey as { decrypt(c: unknown): bigint });
    expect(dec).toBe(1000n);
  }, 15000);
});
