export const Theme = {
  primary: 'cyanBright',
  secondary: 'gray',
  success: 'greenBright',
  error: 'redBright',
  warning: 'yellowBright',
  info: 'blueBright',
  highlight: 'magentaBright',
  text: 'white',
  dim: 'gray',
};

export const Icons = {
  rocket: '🚀',
  key: '🔑',
  link: '🔗',
  folder: '📁',
  checkmark: '✔',
  cross: '✖',
  arrow: '→',
  upArrow: '↑',
  downArrow: '↓',
  dot: '•',
  sparkle: '✨',
  warning: '⚠',
  info: '🛈',
  clock: '⏱',
  skull: '💀',
  search: '🔍',
};
